### PR TITLE
Modal component

### PR DESCRIPTION
**Pull request by HarshwardhanSingh**

### CODE REVIEW

**Comment by iffyuva** [comment]
How can I try this?

**Comment by HarshwardhanSingh** [comment]
@iffyuva just clone this branch and go to /home. I am thinking of creating something like playground for each component for future. Currently `Home` component is our test area. :)

**Comment by kgrz** [comment]
@HarshwardhanSingh on that note, may be add some default code examples on home component and provide an easier entrypoint?

**Comment by HarshwardhanSingh** [comment]
@iffyuva @kgrz Can be tested using storybook

**Pull request merged**
